version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.20.7
    restart: always
    ports:
    - "4477:4477"
    environment:
      PRISMA_CONFIG: |
        secret: utBL2f_?6yQ3U@nzLt^6RyhcHw+=VZ
        port: 4477
        databases:
          default:
            connector: mysql  # or `postgres`
            migrations: true
            host: db
            port: 3306        # or `5432` for `postgres`
            user: root
            password: prisma
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: